### ISSUE TITLE
Extend cisco_snmp_interface.py for setup portAdminSpeed and portDuplex

### ISSUE THREAD

**Issue by michiatlnx** [networklore/ansible-cisco-snmp#5]
It is possible to extend the script for setup portAdminSpeed and portDuplex on interface?
The problem is Cisoco use in this case a seperate CISCO-STACK-MIB
# From CISCO-STACK-MIB
self.portAdminSpeed = "1.3.6.1.4.1.9.5.1.4.1.1.9"
self.portDuplex = "1.3.6.1.4.1.9.5.1.4.1.1.10"
self.portIfIndex = "1.3.6.1.4.1.9.5.1.4.1.1.11"

And works with portIfIndex mapping to ifIndex here:
| --   portIfIndex (11)	
1.3.6.1.4.1.9.5.1.4.1.1.11.1.1 = INTEGER: 10101
1.3.6.1.4.1.9.5.1.4.1.1.11.1.2 = INTEGER: 10102
1.3.6.1.4.1.9.5.1.4.1.1.11.1.3 = INTEGER: 10001
1.3.6.1.4.1.9.5.1.4.1.1.11.1.4 = INTEGER: 10002
1.3.6.1.4.1.9.5.1.4.1.1.11.1.5 = INTEGER: 10003
1.3.6.1.4.1.9.5.1.4.1.1.11.1.6 = INTEGER: 10004
1.3.6.1.4.1.9.5.1.4.1.1.11.1.7 = INTEGER: 10005

The ifIndex are the following interfaces:
IF-MIB::ifDescr.10101 = STRING: GigabitEthernet1/0/1
IF-MIB::ifDescr.10102 = STRING: GigabitEthernet1/0/2
IF-MIB::ifDescr.10001 = STRING: FastEthernet1/0/1
IF-MIB::ifDescr.10002 = STRING: FastEthernet1/0/2
IF-MIB::ifDescr.10003 = STRING: FastEthernet1/0/3
IF-MIB::ifDescr.10004 = STRING: FastEthernet1/0/4
IF-MIB::ifDescr.10005 = STRING: FastEthernet1/0/5

This are the possible values:
portAdminSpeed
Values
1 : autoDetect
2 : autoDetect10100
10 : s10G
64000 : s64000
1544000 : s1544000
2000000 : s2000000
2048000 : s2048000
4000000 : s4000000
10000000 : s10000000
16000000 : s16000000
45000000 : s45000000
64000000 : s64000000
100000000 : s100000000
155000000 : s155000000
400000000 : s400000000
622000000 : s622000000
1000000000 : s1000000000

portDuplex
Values
1 : half
2 : full
3 : disagree
4 : auto

Could you added this or give me a hint how can I write the mapping find function of ifIndex to portIfIndex in python script?

**Comment by ogenstad** [comment]
Hi,

When I wrote these modules Ansible didn't have a way to work with network devices. Since Ansible 2.1 this functionality is built into Ansible. Do you still see any need for this? I would instead point you to the ios_config module, or using Napalm with Ansible.

Best regards
Patrick

**Comment by michiatlnx** [comment]
Hello Patrick,

thanks for your information and the hint.
Our requirements are changed in the meantime, we must not use snmp for config devices anymore.

Best regards
